
## DICTIONARY OF INDICES FOR PLOTTING

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# method to return string with first character converted to lower case
def lc(s): return s[:1].lower() + s[1:]

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# colourmaps applied for each group of indices, depending on meaning of positive values

cmaps = {"pr" : "RdBu",          # wetter
         "pr_r" : "RdBu_r",      # drier
         "temp" : "RdBu_r",      # warmer
         "temp_r" : "RdBu",      # cooler
         "wind" : "PuOr",        # windier
         "wind_r" : "PuOr_r",    # calmer
         "agri" : "PRGn",        # longer growing season
         "other" : "PuOr",
         "other_r" : "PuOr_r"}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# dictionary of indices, giving units, colourmaps and plot labels to be used

var_cv = {'cdd': {'cmap': cmaps["temp"], 
                  'plot_label': 'Cooling degree-days',
                  'units': '1'},
          'clt': {'cmap': cmaps["other"], 
                  'plot_label': 'Total cloud (%)',
                  'units': '%'},
          'csdi': {'cmap': cmaps["temp_r"],
                   'plot_label': 'Number of cold spell days',
                   'units': 'day'},
          'dsmax': {'cmap':  cmaps["pr_r"],
                    'plot_label': 'Maximum length of dry spell (days)',
                    'units': '1'},
          'dsmed': {'cmap': cmaps["pr_r"],
                    'plot_label': 'Median length of dry spell (days)',
                    'units': '1'},
          'dtr': {'cmap': 'PuOr_r',
                  'plot_label': 'Diurnal temperature range tasmax - tasmin (°C)',
                  'units': 'degC'},
          'fwd': {'cmap': cmaps["pr"], 
                  'plot_label': 'Proportion of wet days', 
                  'units': '%'},
          'gdd': {'cmap': cmaps["agri"], 
                  'plot_label': 'Growing degree-days',
                  'units': '1'},
          'gsl': {'cmap': cmaps["agri"],
                  'plot_label': 'Growing season length (days)',
                  'units': '1'},
          'hdd': {'cmap': cmaps["temp_r"],
                  'plot_label': 'Heating degree-days',
                  'units': '1'},
          'hurs': {'cmap': cmaps["other"],
                   'plot_label': 'Relative humidity at 1.5m (%)',
                   'units': '%'},
          'huss': {'cmap': cmaps["other"],
                   'plot_label': 'Specific humidity at 1.5m',
                   'units': '1'},
          'hwdi': {'cmap': cmaps["temp"],
                   'plot_label': 'Number of heatwave days',
                   'units': 'day'},
          'maxsfcWindmax': {'cmap': cmaps["wind"],
                            'plot_label': 'Maximum sustained wind speed at 10m (m s-1)',
                            'units': 'm s-1'},
          'maxsfcWindmaxloc': {'cmap': cmaps["wind"],
                               'plot_label': 'Location parameter for GEV fitted to\nmaximum daily wind speed (m/s)',
                               'units': 'm s-1'},
          'maxsfcWindmaxscale': {'cmap': cmaps["other_r"],
                                 'plot_label': 'Scale parameter for GEV fitted to\nmaximum  daily wind speed (m/s)',
                                 'units': 'm s-1'},
          'maxsfcWindmaxshape': {'cmap': cmaps["other_r"],
                                 'plot_label': 'Shape parameter for GEV fitted to\nmaximum daily wind speed (m/s)',
                                 'units': '1'},
          'maxsfcWindmaxrl20': {'cmap': cmaps["wind"],
                                'plot_label': '20-year return level for GEV fitted to\nmaximum daily wind speed (m/s)',
                                'units': 'm s-1'},
          'maxsfcWindmaxrl50': {'cmap': cmaps["wind"],
                                'plot_label': '50-year return level for GEV fitted to\nmaximum daily wind speed (m/s)',
                                'units': 'm s-1'},
          'maxsfcWindmaxrp20': {'cmap': cmaps["wind_r"],
                                'plot_label': 'Return period for current\n1-in-20-year maximum daily wind speed',
                                'units': '1'},
          'maxsfcWindmaxrp50': {'cmap': cmaps["wind_r"],
                                'plot_label': '50-year return period for current\n1-in-50-year maximum daily wind speed',
                                'units': '1'},
          'maxwsgsmax': {'cmap': cmaps["wind"],
                         'plot_label': 'Maximum gust speed at 10m (m s-1)',
                         'units': 'm s-1'},
          'maxwsgsmaxloc': {'cmap': cmaps["wind"],
                            'plot_label': 'Location parameter for GEV fitted to\nmaximum daily gust speed (m/s)',
                            'units': 'm s-1'},
          'maxwsgsmaxscale': {'cmap': cmaps["other_r"],
                              'plot_label': 'Scale parameter for GEV fitted to\nmaximum  daily gust speed (m/s)',
                              'units': 'm s-1'},
          'maxwsgsmaxshape': {'cmap': cmaps["other_r"],
                              'plot_label': 'Shape parameter for GEV fitted to\nmaximum daily gust speed (m/s)',
                              'units': '1'},
          'maxwsgsmaxrl20': {'cmap': cmaps["wind"],
                             'plot_label': '20-year return level for GEV fitted to\nmaximum daily gust speed (m/s)',
                             'units': 'm s-1'},
          'maxwsgsmaxrl50': {'cmap': cmaps["wind"],
                             'plot_label': '50-year return level for GEV fitted to\nmaximum daily gust speed (m/s)',
                             'units': 'm s-1'},
          'maxwsgsmaxrp20': {'cmap': cmaps["wind_r"],
                             'plot_label': 'Return period for current\n1-in-20-year maximum daily gust speed',
                             'units': '1'},
          'maxwsgsmaxrp50': {'cmap': cmaps["wind_r"],
                             'plot_label': '50-year return period for current\n1-in-50-year maximum daily gust speed',
                             'units': '1'},
          'maxtmax': {'cmap': cmaps["temp"],
                      'plot_label': 'Maximum air temperature on the hottest day at 1.5m (°C)',
                      'units': 'degC'},
          'mintmin': {'cmap': cmaps["temp"],
                      'plot_label': 'Minimum air temperature on the coldest day at 1.5m (°C)',
                      'units': 'degC'},
          'mrso': {'cmap': cmaps["pr"],
                   'plot_label': 'Mean soil moisture at a depth of up to 1m',
                   'units': 'kg m-2'},
          'ncalm': {'cmap': cmaps["wind_r"],
                    'plot_label': 'Number of calm days',
                    'units': '1'},
          'ndhi': {'cmap': cmaps["temp"],
                   'plot_label': 'Number of dangerously warm days (hi > 32°C)',
                   'units': '1'},
          'nwindy': {'cmap': cmaps["wind"],
                     'plot_label': 'Number of windy days',
                     'units': '1'},
          'pdd': {'cmap': cmaps["pr_r"],
                  'plot_label': 'Percentage of dry days followed by another dry day',
                  'units': '%'},
          'pww': {'cmap': cmaps["pr"],
                  'plot_label': 'Percentage of wet days followed by another wet day',
                  'units': '%'},
          'pet': {'cmap': cmaps["pr_r"],
                  'plot_label': 'Accumulated PET (mm)',
                  'units': 'mm'},
          'pr': {'cmap': cmaps["pr"],
                 'plot_label': 'Precipitation rate (mm/day)',
                 'units': 'mm/day'},
          'prc': {'cmap': cmaps["pr"],
                  'plot_label': 'Convective precipitation rate (mm/day)',
                  'units': 'mm/day'},
          'prf': {'cmap': cmaps["pr"],
                  'plot_label': 'Non-convective precipitation rate (mm/day)',
                  'units': 'mm/day'},
          'prcprop': {'cmap': cmaps["pr"],
                      'plot_label': 'Proportion of rainfall due to convection (%)',
                      'units': '%'},
          'prcptot': {'cmap': cmaps["pr"],
                      'plot_label': 'Accumulated precipitation (mm)',
                      'units': 'mm'},
          'pr1day': {'cmap': cmaps["pr"],
                     'plot_label': '1-day total precipitation (mm)',
                     'units': 'mm'},
          'pr5day': {'cmap': cmaps["pr"],
                     'plot_label': '5-day total precipitation (mm)',
                     'units': 'mm'},
          'prsn': {'cmap': cmaps["pr"],
                   'plot_label': 'Snowfall flux at surface (mm/day)',
                   'units': 'mm/day'},
          'psl': {'cmap': cmaps["other"],
                  'plot_label': 'Sea level pressure (hPa)',
                  'units': 'hPa'},
          'r99': {'cmap': cmaps["pr"],
                  'plot_label': '99th percentile of daily precipitation (mm/day)',
                  'units': 'mm/day'},
          'r95ptot': {'cmap': cmaps["pr"],
                      'plot_label': 'Proportion of precipitation (%)',
                      'units': '%'},
          'r99ptot': {'cmap': cmaps["pr"],
                      'plot_label': 'Proportion of precipitation (%)',
                      'units': '%'},
          'rls': {'cmap': cmaps["other_r"],
                  'plot_label': 'Net surface long wave flux (W m-2)',
                  'units': 'W m-2'},
          'rss': {'cmap': cmaps["other_r"],
                  'plot_label': 'Net surface short wave flux (W m-2)',
                  'units': 'W m-2'},
          'rx1day': {'cmap': cmaps["pr"],
                     'plot_label': 'Maximum 1-day precipitation (mm)',
                     'units': 'mm'},
          'rx1dayloc': {'cmap': cmaps["pr"],
                        'plot_label': 'Location parameter for GEV fitted to\nmaximum 1-day precipitation (mm)',
                        'units': 'mm'},
          'rx1dayscale': {'cmap': cmaps["other_r"],
                          'plot_label': 'Scale parameter for GEV fitted to\nmaximum 1-day precipitation (mm)',
                          'units': 'mm'},
          'rx1dayshape': {'cmap': cmaps["other_r"],
                          'plot_label': 'Shape parameter for GEV fitted to\nmaximum 1-day precipitation',
                          'units': '1'},
          'rx1dayrl20': {'cmap': cmaps["pr"],
                         'plot_label': '20-year return level for GEV fitted to\nmaximum 1-day precipitation (mm)',
                         'units': 'mm'},
          'rx1dayrl50': {'cmap': cmaps["pr"],
                         'plot_label': '50-year return level for GEV fitted to\nmaximum 1-day precipitation (mm)',
                         'units': 'mm'},
          'rx1dayrp20': {'cmap': cmaps["pr_r"],
                         'plot_label': 'Return period for current\n1-in-20-year maximum 1-day precipitation',
                         'units': '1'},
          'rx1dayrp50': {'cmap': cmaps["pr_r"],
                         'plot_label': '50-year return period for current\n1-in-50-year maximum 1-day precipitation',
                         'units': '1'},
          'rx5day': {'cmap': cmaps["pr"],
                     'plot_label': 'Maximum 5-day precipitation (mm)',
                     'units': 'mm'},
          'rx5dayloc': {'cmap': cmaps["pr"],
                        'plot_label': 'Location parameter for GEV fitted to\nmaximum 5-day precipitation (mm)',
                        'units': 'mm'},
          'rx5dayscale': {'cmap': cmaps["other_r"],
                          'plot_label': 'Scale parameter for GEV fitted to\nmaximum 5-day precipitation (mm)',
                          'units': 'mm'},
          'rx5dayshape': {'cmap': cmaps["other_r"],
                          'plot_label': 'Shape parameter for GEV fitted to\nmaximum 5-day precipitation',
                          'units': '1'},
          'rx5dayrl20': {'cmap': cmaps["pr"],
                         'plot_label': '20-year return level for GEV fitted to\nmaximum 5-day precipitation (mm)',
                         'units': 'mm'},
          'rx5dayrl50': {'cmap': cmaps["pr"],
                         'plot_label': '50-year return level for GEV fitted to\nmaximum 5-day precipitation (mm)',
                         'units': 'mm'},
          'rx5dayrp20': {'cmap': cmaps["pr_r"],
                         'plot_label': 'Return period for current\n1-in-20-year maximum 5-day precipitation',
                         'units': '1'},
          'rx5dayrp50': {'cmap': cmaps["pr_r"],
                         'plot_label': '50-year return period for current\n1-in-50-year maximum 5-day precipitation',
                         'units': '1'},
          'sdii': {'cmap': cmaps["pr"],
                   'plot_label': 'Wet-day precipitation rate (mm/day)',
                   'units': 'mm/day'},
          'sfcWind': {'cmap': cmaps["wind"],
                      'plot_label': 'Wind speed at 10m (m s-1)',
                      'units': 'm s-1'},
          'sfcWindmax': {'cmap': cmaps["wind"],
                         'plot_label': 'Maximum sustained wind speed at 10m (m s-1)',
                         'units': 'm s-1'},
          'snw': {'cmap': cmaps["pr"],
                  'plot_label': 'Amount of snow on the ground (mm)',
                  'units': 'mm'},
          'spei6': {'cmap': cmaps["pr"],
                    'plot_label': '6-month standardised precipitation-evapotranspiration index',
                    'units': '1'},
          'spi6': {'cmap': cmaps["pr"],
                   'plot_label': '6-month standardised precipitation index',
                   'units': '1'},
          'str': {'cmap': 'PuOr_r',
                  'plot_label': 'Seasonal temperature range tas99 - tas01 (°C)',
                  'units': 'degC'},
          'tas': {'cmap': cmaps["temp"],
                  'plot_label': 'Mean air temperature at 1.5m (°C)',
                  'units': 'degC'},
          'tas01': {'cmap': cmaps["temp"],
                    'plot_label': 'First percentile of daily mean air temperature at 1.5m (°C)',
                    'units': 'degC'},
          'tas99': {'cmap': cmaps["temp"],
                    'plot_label': '99th percentile of daily mean air temperature at 1.5m (°C)',
                    'units': 'degC'},
          'tasmax': {'cmap': cmaps["temp"],
                     'plot_label': 'Daily maximum air temperature at 1.5m (°C)',
                     'units': 'degC'},
          'tasmin': {'cmap': cmaps["temp"],
                     'plot_label': 'Daily minimum air temperature at 1.5m (°C)',
                     'units': 'degC'},
          'tmin10p': {'cmap': cmaps["temp_r"],
                      'plot_label': 'Number of cold nights',
                      'units': 'day'},
          'tmax10p': {'cmap': cmaps["temp_r"],
                      'plot_label': 'Number of cold days',
                      'units': 'day'},
          'tmax90p': {'cmap': cmaps["temp"],
                      'plot_label': 'Number of hot days',
                      'units': 'day'},
          'tmin90p': {'cmap': cmaps["temp"],
                      'plot_label': 'Number of warm nights',
                      'units': 'day'},
          'tr': {'cmap': cmaps["temp"],
                 'plot_label': 'Number of tropical nights',
                 'units': 'day'},
          'uas': {'cmap': cmaps["wind"],
                  'plot_label': 'Eastward wind at 10m (m s-1)',
                  'units': 'm s-1'},
          'vas': {'cmap': cmaps["wind"],
                  'plot_label': 'Northward wind at 10m (m s-1)',
                  'units': 'm s-1'},
          'wsgsmax': {'cmap': cmaps["wind"],
                      'plot_label': 'Maximum gust speed at 10m (m s-1)',
                      'units': 'm s-1'},
          'wsmax': {'cmap': cmaps["pr"],
                    'plot_label': 'Maximum length of wet spell (days)',
                    'units': '1'},
          'wsmed': {'cmap': cmaps["pr"],
                    'plot_label': 'Median length of wet spell (days)',
                    'units': '1'}}

